### ISSUE TITLE
Добавить возможность запускать симуляцию с выбором роли

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#101]
Седой, обдумай можно ли реализовать такое по аналогии с командой newmob role
Особо сильно это не нужно, но было бы удобно спавниться за персонажа с одеждой и смотреть как он смотрится на фоне карты

Я примерно вижу это так:
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/1d2c464d-8f86-4500-bae6-a9da669dceef)
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/21a8d7c6-1fd9-4539-8f44-eb889f4764b1)

**Comment by Irmos9** [comment]
Седой, обдумай можно ли

**Comment by Yobas** [comment]
Парни эта фича уже есть в меню симуляции. Она вам нужна продублированная в контекстном меню? @Sranych @Irmos9

**Comment by Sranych** [comment]
@Yobas типа там можно выбрать роли которых нет в режиме?

**Comment by Yobas** [comment]
> @Yobas типа там можно выбрать роли которых нет в режиме?

Роль которая не прописана в режиме не предназначена для спавна в этом режиме.

**Comment by Sranych** [comment]
@Yobas так у нас же есть команда newmob role=RBum, функционал привязанный к ней нельзя заюзать в этой идее?

**Comment by Yobas** [comment]
> @Yobas так у нас же есть команда newmob role=RBum, функционал привязанный к ней нельзя заюзать в этой идее?

Он не создает персонажа конкретной роли. Он просто берет экипировку с ней. Но даже это в некоторых случаях может вызывать ошибки, например при спавне бомжей или обывал от Грязноямска

**Comment by Sranych** [comment]
@Yobas ну давай сделаем и ограничим ошибки?

**Comment by Yobas** [comment]
> @Yobas ну давай сделаем и ограничим ошибки?

Ну тогда я просто расширяю список спавна с точки
Первый пункт остается неизменным как раньше, а второй открывает список вообще всех ролей для всех режимов. При выборе роли будет спавниться такой же системный персонаж, но с одеждой выбранной роли. 
Идёт?

**Comment by Sranych** [comment]
@Yobas Да, ! Это реальня движуха

**Comment by Yobas** [comment]
@Sranych пойдёт?
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/35444748/1e1a545e-9f2c-4fe7-9ab1-3c85746db287)
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/35444748/65d7606a-c929-4167-9db6-5e8f07e2791f)
