### ISSUE TITLE
Идеологии в Грязноямске

### ISSUE THREAD

**Issue by Yobas** [Relicta-Team/ReSDK_A3.vr#113]
Голова при заходе выбирает политический строй:
- ☑**Царство Подземное** (монархия): Голова - царь Грязноямска и принимает все решения, которым все бесприкословно следуют под страхом смерти. Жители и хвосты будут порабощены или уничтожены. Работники различных сфер являются бесправными рабами Головы. Огнестрельное оружие не в почете. Ополчение вооружено мечами и по первому указу отрубит головы всем ослушавшимся. В Расход уходит Голова, его охрана и люди, которых он захочет взять с собой. А ещё Голове дается корона...
- ☑**Путь Фугу** (теократия) - Голова принимает решения в соответствии с устоями церкви Фугу и Аббатом. **(доступно только если есть Аббат)**. Смотритель становится инквизитором и подчиняется приказам как Головы, так и Аббата. В Расход уходит вся церковь, инквизиция и сам Голова.
-  ☑**Республика Железной Руки** (военная диктатура) - Голова - верховный главнокомандующий. Вся власть в руках ополчения. Расстрелы и пропаганда - обычное дело. В Расход уходят только командование (Ополчение и Голова)
- ☑**Совет Пяти** (социализм, демократия) - Решения по любым вопросам принимаются коллективно группой людей (Голова, Смотритель, Барник, Лекарь, Бригадир и все эти роли должны быть заняты). Идеология хорошо работает только когда много людей в Грязноямске. В Расход могут уйти все желающие.
- (WIP) **Пещероград** (племенная республика) - Голова и жители - кочевники, пришедшие в пустующий город и занявшие его. В основе общность и отсутствие материальных ценностей (*кочевникам ни к чему звяки*). В Расход должны уйти все кочевники.
- ~~**Звонкая Долина** (капитализм) - деньги есть двигатель всего. Каждый вовлечен в мир бизнеса и торговли. Ополчение продажно и может быть куплено тем, у кого больше всего средств. В Расход можно уйти, купив билет у Головы. У всех немного больше средств со старта.~~
- ☑**Старый Добрый Грязноямск** - классический Грязноямск, в котором Голова сам решает как управлять городом. Доступно для игроков на Голове, которые отыграли более имеют уровень доступа выше или равный ACCESS_PLAYER и отыгравших более 50 раундов.

Предварительные необходимые вещи для интеграции:
- [x] - добавить корону в библиотеку, сделать прокси для неё
- [x] - добавить кнопку выбора строя для головы. так же сделать вывод сообщения при пробуждении.
- [x] - игровые описание строев и вывод всему серверу текущего строя.
- [x] - строй вносится всем персонажам в воспоминания.
- [x] - показать строй в конце раунда.
- [x] - проверить работу таймера если голова ничего не выбрал
- [x] - Удалить всю пищу, огнестрел, медицину в Пещерограде. Спавнить на ролях через контейнеры.
- [x] - ~~В пещерограде жруны бесконечные и могут придти в любой момент~~

**Comment by WhiTMBster** [comment]
Можно добавить "классический грязноямск", где голова сам выбирает как все будет работать. Вообще, судя по всему строи меняют не только ролеплей тему, но и сам геймплей с точки зрения вооружения ополчения, короны, возможно даже названиями ролей. Хотелось бы, чтобы каждый из строев как-то менял эти аспекты во время раунда. Те же билеты в капиталистическом грязноямске. Или чтобы при капитализме деньги использовались для ВСЕГО, вплоть до работы некоторых устройств на звяках. Или чтобы в таком случае выдавали больше звяков игрокам, дабы им было на что тратить, или что-то терять.

**Comment by Yobas** [comment]
> Можно добавить "классический грязноямск", где голова сам выбирает как все будет работать. Вообще, судя по всему строи меняют не только ролеплей тему, но и сам геймплей с точки зрения вооружения ополчения, короны, возможно даже названиями ролей. Хотелось бы, чтобы каждый из строев как-то менял эти аспекты во время раунда. Те же билеты в капиталистическом грязноямске. Или чтобы при капитализме деньги использовались для ВСЕГО, вплоть до работы некоторых устройств на звяках. Или чтобы в таком случае выдавали больше звяков игрокам, дабы им было на что тратить, или что-то терять.

Добавил **Старый Добрый Грязноямск**

**Comment by WhiTMBster** [comment]
ПЕЩЕРОГРАД, как понятно, превращает грязноямск в обитель бомжей и кочевников. Света нету, ибо сам город тыщу лет как мертв, а потому прибывшие, приходящие сюда — полу-дикари, у которых дикарские и примитивные порядки. Естественно их не будет интересовать звяки. А потому, дом торгаша перерабатывается в подобие СКЛАДА.

Складом будет заведовать КЛАДОВЩИК (Как раньше на 2017). Только без звяков вообще. 
На складе будут присутствовать:
 Самые важные и необходимые пищевые продукты и припасы. В данном случае яйца, мука, масло, молоко, соль, перец и мясо. 
 ГРИБЫ. Можно добавить грибочки из пещер, не только те, которые для питания.
Инструменты. Примитивные топоры, ножи, дубинки, а также инструменты вроде лопаты или монтировки.
Одежда. Одежда самая обычная, примитивная. Просто обноски и какие-нибудь тряпки, маски-тряпки и накидки, шапки.
Факела, свечи и лампы.
Спички.
Сумки, вроде рюкзаков или мешочков с деньгами.
Медицина, в основном иголки, тряпки-бинты и болеутоляющее.
АЛКОГОЛЬ.

Оружие, хирургические инструменты и прочие рольные вещи можно не добавлять. Пусть будут храниться в специально отведенных для этого местах, где им и место.
