### ISSUE TITLE
Новые модели

### ISSUE THREAD

**Issue by Yobas** [Relicta-Team/ReSDK_A3.vr#115]
# Основные 
- Руки, ноги. Засранная текстура. Текстуру могу нарисовать сам, но мне нужна развертка.
- Кнут. Большой кнут для битья рабов. Рукоятка кнута с кожаным материалом. Реф рукоятки:

<img src="https://github.com/Relicta-Team/ReSDK_A3.vr/assets/35444748/ef6deb50-c8a7-4fbb-80c1-b3f6a161a6a4" width="300" height="300">

- Черная горстка (модель от соли) с темной текстурой. Для перца, чая, пороха и тд
- Пачки патронов. Разных 2-4 штук. Дробь, пистолет, винтовки.
- Магазины для оружия. Патроны внутри магазина не должны отображаться. Рефы ниже:
Пистолетный:
<img src="https://github.com/Relicta-Team/ReSDK_A3.vr/assets/35444748/94024470-4a52-4593-9ee0-b9ba9716caa2" width="300" height="300">

Автоматный под товарища:
<img src="https://github.com/Relicta-Team/ReSDK_A3.vr/assets/35444748/73983076-0a3d-4609-a709-9facf775fc90" width="300" height="300">

Автоматный под мерзавца:
<img src="https://github.com/Relicta-Team/ReSDK_A3.vr/assets/35444748/98bc3805-37d3-4e15-98f4-b935faf3e969" width="300" height="300">

Винтовочный для навертышей и СВТ:
<img src="https://github.com/Relicta-Team/ReSDK_A3.vr/assets/35444748/ca3a028a-4c90-406a-9225-80ee17d318ac" width="300" height="300">

- Поезд.
- Плакаты: 
    - Плакат где чумазёда ублажает прекрасную леди из Канавы. 
    - Плакат флага Новой Армии (можно взять с доски миро).

----

# Низкий приоритет
- Универсальная модель одежды, лежащей на земле.

**Comment by 7kaiden7** [comment]
Мне срочно нужен поезд красивый крутой а ещё я хочу недоделанные звяки и заготовки под них. Горки чая разных цветов.

**Comment by WhiTMBster** [comment]
Добавить плакаты, изображения, какие-нибудь простейшие картины без рамок. Банально для окружения. Например, добавить флаг НА (Уже существует в диздоке), который можно повесить на здания НА на окопово и других картах.
Добавить иные бутылки или просто текстурки к уже существующим бутылкам.
Добавить РАЗНЫЕ пачки к патронам (Пачка для пистолетных, ружейных и винтовочных) и РАЗНЫЕ магазины. Хотя бы один магазин на все винтовочные и пистолетные магазины. С патронами (если есть те, которые используют одинаковые модели) тоже самое.
ОДЕЖДА. Предлагаю универсальную модель для одежды и брони. **Не обязательно.** 
Модель для сумок/рюкзаков.

**Comment by Yobas** [comment]
@7kaiden7 
- Поезд - **Добавил**
- Недоделанные звяки (почти завершённый вариант) - **Берем обычный звяк и переименовываем. Слишком режимонаправленные объекты не стоит добавлять**
- **Заготовки под звяки** - выше написал. Тут могу предложить добавить *слитки* разных цветов.
- Бракованный звяк разломанный пополам (если трудно то сделай что-то подобное) - **переименовать обычные звяки**
- Плакат где чумазёда ублажает прекрасную леди из Канавы **неплохо было бы скинуть реф или нарисовать**

**Comment by Yobas** [comment]
@WhiTMBster по пунктам:
- Плакаты: кроме НА дай рефы, примеры или нарисуй сам. **НА плакат внёс**
- Бутылки уже есть. 4 штуки и это только с реликты:
![Безымянный](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/35444748/05ea123e-ae59-4fbe-8c78-1632d93950b9)
- Патронопачки и магазины - **Внёс**
- Одежда на земле - **внёс в лоуприорити**
- Рюкзаки - не совсем понятно про какие рюкзаки идёт речь. Все сумки кроме армовской новой вешаются через прокси и на земле лежат так же как и на спине.

**Comment by Sranych** [comment]
Меня всё устраивает

**Comment by Sranych** [comment]
Промежуточные итоги что бы не забыть

**Что готово:**
- Рука
- Нога
- Рукоятка кнута
- Пачки патронов
- Пистолетный магазин
- Автоматный магазин

**Что не готово:**
- Винтовочный для СВТ
- Автоматный под мерзавца
- Плакаты
- Универсальная модель одежды

**Что идёт нахуй:**
- Поезд

**Comment by 7kaiden7** [comment]
**САМ ИДИ НАХУЙ СРАНИЧ!!!!!!**

**Comment by Yobas** [comment]
Новые модели добавлены
