### ISSUE TITLE
Панель навыков

### ISSUE THREAD

**Issue by 7kaiden7** [Relicta-Team/ReSDK_A3.vr#116]
Распределить навыки на категории

Холодное оружие:
- Дубины, копья, мечи, ножи, кнтуы

Огнестрел:
- Пистолеты, винтовки, дробовики, 

Движение:
- Воровство, скрытность, акробатика

Знания(ремесло):
- Химичество, Инженерия, ловушки, ремонт, кузнечество, взлом, первая помощь, хирургия, знания пещер, готовка, фермерство

**Comment by Yobas** [comment]
Я правильно понимаю, что идёт речь о распределении списка навыков в окне, открываемом при нажатии по "Навыки" в правом меню?

**Comment by Sranych** [comment]
@Yobas yes да, верно всё
Так и хотим

**Comment by Yobas** [comment]
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/35444748/a3d2b2bf-68e1-46e0-9226-590ba7faf3f8)
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/35444748/1d6b5d32-6333-489d-9ca0-a8e3d3eacca2)

**Comment by 7kaiden7** [comment]
| Ближний бой |

**Comment by Yobas** [comment]
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/35444748/a11c5d16-1629-480d-b41b-3c5a5db0daec)

**Comment by Sranych** [comment]
**[БЛИЖНИЙ БОЙ]**

**Comment by Yobas** [comment]
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/35444748/9f84289f-5eb9-4eb4-8ac2-561eb013af05)

**Comment by Yobas** [comment]
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/35444748/365f15fc-3bb9-446a-8674-4c30fd51c3ac)

**Comment by Yobas** [comment]
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/35444748/3042a977-4b79-4048-9eee-1bf091839e53)

**Comment by Yobas** [comment]
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/35444748/1635b766-1b75-459b-a0fd-08ff24ef649f)
