### ISSUE TITLE
Hands & Body

### ISSUE THREAD

**Issue by 7kaiden7** [Relicta-Team/ReSDK_A3.vr#117]
Когда персонаж загрязняется, иконки на интерфейсе становятся грязными ( накладывается текстура грязи разной стадии)

**Comment by Yobas** [comment]
@7kaiden7 нарисуй пж png с грязью и альфаканалом.

**Comment by Yobas** [comment]
Видов грязи нужно 3-5 штук. От незначительной до полностью засранной.

**Comment by Yobas** [comment]
@7kaiden7 есть движения по таске?

**Comment by 7kaiden7** [comment]
Забыл вообще о ней, у меня сейчас опять тех работы от провайдера. Как только доступ в инет появится - сделаю грязь

**Comment by 7kaiden7** [comment]
Короче если сегодня появится интернет, то грязь тоже

**Comment by 7kaiden7** [comment]
[gryazyka.zip](https://github.com/Relicta-Team/ReSDK_A3.vr/files/12684548/gryazyka.zip)
Шоколадный поезд приближается к станции! Идите мыть руки!
