### ISSUE TITLE
Тачки, инвалидные коляски

### ISSUE THREAD

**Issue by 7kaiden7** [Relicta-Team/ReSDK_A3.vr#118]
Сделать так, чтобы другой человек мог управлять тачкой или коляской когда в ней сидит другой ( не всегда у инвалидов есть руки )

**Comment by Yobas** [comment]
Сразу говорю что это будет выглядеть очень уёбищно. И коляски и тачки будут просто ездить по земле без анимаций крутящихся колёс. Такой вариант устраивает?

**Comment by 7kaiden7** [comment]
невалид.. бедные инвалиды
