### ISSUE TITLE
Перерисовать иконки инвентаря

### ISSUE THREAD

**Issue by Yobas** [Relicta-Team/ReSDK_A3.vr#120]
9 слотов. Стилизованные картинки с альфа-каналом черного цвета.

**Comment by Yobas** [comment]
@7kaiden7 это Вам.

**Comment by 7kaiden7** [comment]
[persona.zip](https://github.com/Relicta-Team/ReSDK_A3.vr/files/12466990/persona.zip)

**Comment by Yobas** [comment]
> [persona.zip](https://github.com/Relicta-Team/ReSDK_A3.vr/files/12466990/persona.zip)

в пятницу во второй половине дня проверю/добавлю

**Comment by 7kaiden7** [comment]
![righthandnew](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/139656223/3906f1d2-d5fd-43f9-b80f-dfc2427da2f2)
![beltnew](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/139656223/d1a17807-5c5d-479e-936f-fc44cde32ddf)
![lefthandnew](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/139656223/cc59cc45-6c95-473c-9f83-e24ff13fefc1)
Поправки в иконки ремня и рук

**Comment by Yobas** [comment]
@7kaiden7 128x128

**Comment by 7kaiden7** [comment]
[belt&hands.zip](https://github.com/Relicta-Team/ReSDK_A3.vr/files/12491048/belt.hands.zip)
