### ISSUE TITLE
После запуска симуляции обратно разворачиваются свёрнутые категории в библиотеке

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#126]
**Шаги:**
1. В редакторе развернуть несколько категорий, например IStruct, Cunstructions, RailBase, SmallPole
2. Свернуть категорию SmallPole
3. Запустить симуляцию и выйти из неё

**Фактический результат:**
Обратить внимание, категория SmallPole снова развёрнута в редакторе.

**Comment by Yobas** [comment]
Напиши порядок действия для воспроизведения чтобы не забыть
