### ISSUE TITLE
Добавить возможность задать разный поворот для каждой точки в конфиге для кроватей

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#127]
Есть такая кровать
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/1ad09c92-39bf-408c-8a3b-a4103cec830a)
Нужна возможность, в конфиге задать разный поворот для каждой точки

Вот эта кровать по конфигу
editor_attribute("EditorGenerated")
class(DoubleCitizenBed1) extends(DoubleArmyBed)
	var(model,"ml\ml_object_new\ml_object_2\decor\bed_original1.p3d");
	getter_func(getChairOffsetPos,[[0 arg 0.1 arg -0.55] arg [0 arg -0.3 arg 0.55]]);
	getter_func(getChairOffsetDir,0);
endclass

**Comment by Yobas** [comment]
@Sranych оказывается возможность настройки разных поворотов для каждой точки уже имплементировано в коде. Замени свою строчку `getter_func(getChairOffsetDir,0);` на:
```sqf
getter_func(getChairOffsetDir,[0 arg 180]);
```
- Первый элемент 0 относится к нижней полке в позиции `[0 arg 0.1 arg -0.55]`
- Второй элемент 180 относится к верхней полке в позиции `[0 arg -0.3 arg 0.55]`
