### ISSUE TITLE
Аспект "Все двери украли"

### ISSUE THREAD

**Issue by 7kaiden7** [Relicta-Team/ReSDK_A3.vr#141]
Переделать аспект чтобы не все двери стальные пропадали, а только некоторые в рандомном порядке.

**Comment by 7kaiden7** [comment]
Аргумент от сраныча что аспект хуйня

**Comment by Sranych** [comment]
Я предлагаю переделать этот аспект в сторону уменьшения количества спизженных дверей по причине того что спизживание дверей вообще никак не аргументировано в самой игре
А если будет спизжено, допустим только 30% железных дверей, это уже не так ебано, и можно реально сослаться на воров

**Comment by Yobas** [comment]
Окей, делаем
