### ISSUE TITLE
Обдумать как реализовать изменение статов персонажа в редакторе

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#148]
Сейчас проблемы с тем что ограничена стрельба в симуляции, оружие вылетает из рук, ограничен.
Обдумать вариант как можно будет реализовать функционал изменения статов персонажа перед запуском симуляции.

**Comment by Yobas** [comment]
Добавить новую настройку в меню "Применить статистики роли при запуске симуляции через контекстное меню". Ну и реализовать

**Comment by Yobas** [comment]
Заходить в симуляцию за роль у которой есть нужные статы
