### ISSUE TITLE
Bugs #139115a

### ISSUE THREAD

**Issue by Yobas** [Relicta-Team/ReSDK_A3.vr#153]
- [x] No item icons
- [x] Pie piece - cant eat
- [x] Disable candles in Dirtpit (Nomads)
- [x] Грязь спавнится в стенах и если там полный рандом в спавне, то может загородить важные входы и выходы
- [x] Застаканные и перевёрнутые пачки патронов у торгаша в злачнике
- [x] Застаканная одежда у бандитов злачнике

**Comment by 7kaiden7** [comment]
Грязь спавнится в стенах и если там полный рандом в спавне, то может загородить важные входы и выходы

**Comment by Sranych** [comment]
- Застаканная одежда у бандитов злачнике
- Застаканные и перевёрнутые пачки патронов у торгаша в злачнике
