### ISSUE TITLE
Реализовать функционал запрета имён в реликте

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#165]
Ограничить ебанистическое поведение людей когда они придумывают себе тупорые имена, например такие как:
- Ебатель Детей
- Табурет Диванов
- Двач Тредов
- Володарь Пулин
- Мамут Рахал
- Пидор Злобный
- Гандон Ебаный
- Залупа Мандариновая
И другие

**Comment by 7kaiden7** [comment]
Добавить функцию для администратора чтобы он мог менять имя игрока во время игры

**Comment by Yobas** [comment]
> Добавить функцию для администратора чтобы он мог менять имя игрока во время игры, ибо по ключевым словам запрет имён это сложно и всё записать не реально.

Данная проблема отлично решается комбинацией *взрыв головы* + *запрет на кастомное имя персонажа*

**Comment by Yobas** [comment]
@Sranych оформляйте заголовки задач нормально пожалуйста (без мата)

**Comment by Yobas** [comment]
@Sranych я постараюсь сегодня выкатить, но скорее всего всем юзерам потребуется задеплоить бд, так как она обновится.

**Comment by Yobas** [comment]
Осуществление блокировки настроек персонажа происходит через команды. При запросе блокировки открывается список доступных полей, которые можно заблокировать. При блокировке для игрока, находящегося на сервере будет выполнен сброс всех сохраненных персонажей, а так же обнуление связанной настройки.

Доступные команды:
- `bancharsetting NAME` - где `NAME` является именем персонажа, для которого применяется данная команда. Открывает листбокс, в котором предлагается выбрать название настройки для блокировки. По выполнении запроса результат отображается в чате (успех/провал).
- `unbancharsetting NAME` - где `NAME` является именем персонажа, для которого применяется данная команда. Для разблокировки игрок должен находится на сервере. По выполнении запроса результат отображается в чате (успех/провал).
- `getbancharsettings NAME` - где  `NAME` является именем персонажа, для которого применяется данная команда. Открывает текстбокс со списком заблокированных имен свойств (системное представление)

> Примечание: регистр имен не учитывается.

Перечисленные выше команды доступны для уровня ACCESS_ADMIN и выше.
