### ISSUE TITLE
Категории лиц в лобби

### ISSUE THREAD

**Issue by Yobas** [Relicta-Team/ReSDK_A3.vr#199]
Заменить виждет листа лиц персонажей на дерево.
Придумать какие будут категории и разделить их.

**Comment by Sranych** [comment]
Можно сделать по возрасту, цвету кожи пещерный-белый/чумазёда/чинчёнг, молодой/зрелый/старый

**Comment by Yobas** [comment]
Текущий дамп мужских лиц:
- persianhead_a3_01
- persianhead_a3_02
- persianhead_a3_03
- persianhead_a3_04_a
- persianhead_a3_04_l
- persianhead_a3_04_sa
- whitehead_01
- whitehead_02
- whitehead_03
- whitehead_04
- whitehead_05
- whitehead_06
- whitehead_07
- whitehead_08
- whitehead_09
- whitehead_10
- whitehead_11
- whitehead_12
- whitehead_13
- whitehead_14
- whitehead_15
- whitehead_16
- whitehead_17
- whitehead_18
- whitehead_19
- whitehead_20
- whitehead_21
- whitehead_22_a
- whitehead_22_l
- whitehead_22_sa
- africanhead_01
- africanhead_02
- africanhead_03
- greekhead_a3_01
- greekhead_a3_02
- greekhead_a3_03
- greekhead_a3_04
- greekhead_a3_10_a
- greekhead_a3_10_l
- greekhead_a3_10_sa
- asianhead_a3_01
- asianhead_a3_02
- asianhead_a3_03
- tanoanhead_a3_01
- tanoanhead_a3_02
- tanoanhead_a3_03
- tanoanhead_a3_04
- tanoanhead_a3_05
- tanoanhead_a3_06
- tanoanhead_a3_07
- tanoanhead_a3_08
- asianhead_a3_04
- asianhead_a3_05
- asianhead_a3_06
- asianhead_a3_07
- greekhead_a3_11
- greekhead_a3_12
- greekhead_a3_13
- greekhead_a3_14
- whitehead_23
- barklem
- mavros
- sturrock
- ioannou
- whitehead_24
- whitehead_25
- whitehead_26
- whitehead_27
- whitehead_28
- whitehead_29
- whitehead_30
- whitehead_31
- whitehead_32
- livonianhead_1
- livonianhead_2
- livonianhead_3
- livonianhead_4
- livonianhead_5
- livonianhead_6
- livonianhead_7
- livonianhead_8
- livonianhead_9
- livonianhead_10
- russianhead_1
- russianhead_2
- russianhead_3
- russianhead_4
- russianhead_5
- tanoanhead_a3_09
```

**Comment by Yobas** [comment]
Индексы примерных категорий:
churos: 0-2,47-50,61
camo: 3-5,27-29,37-39
white: 6-26,33,34,55-59,62-63,65,67-80,82,85,86
black: 30-32,43-46,60
old: 35,36,64,66,81,83,84,88
china: 40-42,51-54,87

**Comment by Yobas** [comment]
> Можно сделать по возрасту, цвету кожи пещерный-белый/чумазёда/чинчёнг, молодой/зрелый/старый

Разделять по возрасту плохая идея, так как старых мало, они практически все белые и нет явной зависимости с возрастом. Будет разделение только по национальности. Наверное 4 расы, камуфляжные рожи будут вырезаны

**Comment by Stellarthoughts** [comment]
@Yobas Камуфляжные в общем-то не подходят игре с самого начала, но люди их адаптировали в ролеплей по типу "ты че такой грязный?".

**Comment by Yobas** [comment]
Добавляем ещё пак лиц к следующей обнове. Ещё кучу мужских и женских.
