### ISSUE TITLE
Баг с открытием контейнера на весь экран

### ISSUE THREAD

**Issue by 7kaiden7** [Relicta-Team/ReSDK_A3.vr#208]
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/139656223/c5894ffb-8276-43d6-865b-7d96b5cfe9a0)
**TAB + E** с нацеленным курсором на контейнер. Делать **быстро** и **много раз**

**Comment by 7kaiden7** [comment]
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/139656223/7ac79a81-57bf-4ef5-a67c-8a1f7cd2ffcc)
Более подробный скриншот

**Comment by Yobas** [comment]
Ошибка происходит по следующей причине: Клиент считает, что инвентарь открыт и синхронизирует объекты. Происходит это потому, что удаление виджета контейнера происходит не моментально а с некоторой задержкой для плавно анимации. При синхронизации не создаётся бокс контейнера и все виджеты помещаются на дисплей инвентаря вместо виджета контейнера.
Решение:
1. Преобразовать переменную проверки открытия контейнера в функцию
2. Добавить проверку существования объекта виджета контейнера

**Comment by Yobas** [comment]
Требуется изменение функции `inventory_unloadContainerMenu`.
Варианты:
1. Переместить `inventory_isOpenContainer` до отложенного вызова.
2. Передать виджет контейнера в параметры отложенного вызова и обнулить ссылки на основные объекты контейнера 
в `inventory_containerWidgets`

**Comment by Yobas** [comment]
Тесты и патч выпустить сегодня ночью

**Comment by Yobas** [comment]
> Требуется изменение функции `inventory_unloadContainerMenu`. Варианты:
> 
> 1. Переместить `inventory_isOpenContainer` до отложенного вызова.
> 2. Передать виджет контейнера в параметры отложенного вызова и обнулить ссылки на основные объекты контейнера
>    в `inventory_containerWidgets`

Не подошло. Требуется какая-то задержка

**Comment by Yobas** [comment]
Задержка не всегда спасает. Чтобы не рефакторить весь компонент контейнера на стороне клиента, вернусь к варианту: https://github.com/Relicta-Team/ReSDK_A3.vr/issues/208#issuecomment-1748380289 с небольшими изменениями:
Нужно просто добавить проверку существует ли виджетгруппа для контейнера. Также провести дополнительный анализ на наличие поломки логики.

**Comment by Yobas** [comment]
Тестовое решение в https://github.com/Relicta-Team/ReSDK_A3.vr/commit/4bc381ef58cefe1a3d6cbe650d7fc9ff379245c1 на ветке development. Просьба протестировать

**Comment by Sranych** [comment]
Я проверил у себя, воспроизвести не смог, но по этим же шагам есть проблема с исчезновением слота пояса
![20231006175419_1](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/23dd76ac-e167-4ab8-9f7a-61c479394992)

**Comment by Yobas** [comment]
> Я проверил у себя, воспроизвести не смог, но по этим же шагам есть проблема с исчезновением слота пояса ![20231006175419_1](https://user-images.githubusercontent.com/73469482/273247656-23dd76ac-e167-4ab8-9f7a-61c479394992.jpg)

Дай пожалуйста порядок действий как воспроизвести проблему

**Comment by Yobas** [comment]
Это никак не могло повлиять на развертку слотов. Их код не затронут

**Comment by Sranych** [comment]
Навести курсор на контейнер, спамить TAB + E, персонаж должен быть одет. При открытии инвентаря курсор центрируется на слоте одежды, это как-то связано, получается так что мы пытаемся одновременно открыть контейнер и инвентарь, нужно попасть в таймер.

**Comment by Yobas** [comment]
> Навести курсор на контейнер, спамить TAB + E, персонаж должен быть одет. При открытии инвентаря курсор центрируется на слоте одежды, это как-то связано, получается так что мы пытаемся одновременно открыть контейнер и инвентарь, нужно попасть в таймер.

Я всю ночь тестил этот баг. С разверткой слотов ни разу проблем не было. Ты можешь переключиться на свою ветку и попробовать воспроизвести эту ошибку?

**Comment by Yobas** [comment]
Попробовать следующий вариант :
Локать ввод хандлеров инвентаря если они в состоянии развёртки или свертки
