### ISSUE TITLE
Свечу можно установить в держатель для факела и она будет отображаться как факел

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#210]
Если взять свечу, и установить её в держатель для факела, то она будут отображаться как факел и светить так же как факел. 
Если снять свечу с держателя, она снова превращается в свечу.
Такая же проблема с керосиновой лампой

**Comment by Sranych** [comment]
То же самое со спичкой

**Comment by Yobas** [comment]
Прошу проверить на дев-ветке
