### ISSUE TITLE
Уменьшить накопление грязи

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#212]
Уменьшить интенсивность текстуры грязи, слишком ярко выраженная текстура

**Comment by Yobas** [comment]
@Sranych По интенсивности давай сам поиграйся. Настрой как считаешь нужным и оформляй PR.
Настройка в файле `Src/host/GameObjects/ConstantAndDefines/Cleanable.h`
https://github.com/Relicta-Team/ReSDK_A3.vr/blob/121de18cfc531d62a96a12c3aa668bf08c7ab65b/Src/host/GameObjects/ConstantAndDefines/Cleanable.h#L15

Например, чтобы уменьшить верхний предел видимости грязи нужно поменять **1** на **0.5**:
*#define GERM_CONV_VALUE_TO_OPACITY(val) linearConversion [0,GERM_COUNT_MAX,val,* **0.5** *,0,true]*
Чтобы запачкать предмет - клади его на грязные поверхности.

Механика загрязнения достаточно комплексная и не умещается в грядущий релиз - сделал на неё отдельную таску.

**Comment by Yobas** [comment]
PR #220
