### ISSUE TITLE
Добавить антистрейф

### ISSUE THREAD

**Issue by Yobas** [Relicta-Team/ReSDK_A3.vr#214]
При постоянном дроче кнопок управления, например влево/вправо персонаж должен падать.
Данные:
- Производится проверка в цикле каждые n секунд:
- Время последнего нажатия каждой из клавиш управления хранится в памяти.
- При слишком маленьких таймингах вызываем событие на сервер падению персонажа. Событие определено только для сущностей типа Mob и всех дочерних.

**Comment by Stellarthoughts** [comment]
Больше, больше казусов за тупые телодвижения! Моя школа. Плюсую
