### ISSUE TITLE
В скором времени сервер дискорда будет 3 уровня. Вот новое оформление.

### ISSUE THREAD

**Issue by 7kaiden7** [Relicta-Team/ReSDK_A3.vr#221]
![relictadiscord](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/139656223/2af062a3-453a-40e5-a939-7dc9e62ee7f4)
![bannerdiscord](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/139656223/e8f8a535-e1e3-4e41-bac4-ce14271eefa1)
Сегодня с 11:00 до 21:00

**Comment by Stellarthoughts** [comment]
А где.

**Comment by 7kaiden7** [comment]
Очередь на буст ёмаё

**Comment by 7kaiden7** [comment]
**меня ОБМАНУЛИ**
