### ISSUE TITLE
Слои в ReSDK

### ISSUE THREAD

**Issue by 7kaiden7** [Relicta-Team/ReSDK_A3.vr#225]
Умоляю при нажатии на обьект добавить кнопку в контекстное меню "Добавить в слой  'ПОЛ' "
Естественно если это реализуемо и не время затратно. Жду ответную связь

**Comment by Yobas** [comment]
Почему именно пол?

**Comment by 7kaiden7** [comment]
Дело не в этом, просто к примеру привёл

**Comment by Yobas** [comment]
Слоев много и все не уместятся в контекстном меню. Объясни как это должно работать по-твоему?

**Comment by 7kaiden7** [comment]
При нажатии ты видишь все доступные слои. Если их много можно сделать прокрут колесиком мыши этих слоев.

**Comment by 7kaiden7** [comment]
Это облегчит строение карт очень сильно

**Comment by Yobas** [comment]
> При нажатии ты видишь все доступные слои. Если их много можно сделать прокрут колесиком мыши этих слоев.

Контекстное меню не поддерживает прокрутку. Можно сделать через открытие отдельного окна со списком слоёв. Более того, эта фича будет назначать в выбранный слой только один объект, так как контекстное меню применяется к единственному объекту, по которому нажали ПКМ. 
Учитывая все эти нюансы не уверен, что это сильно ускорит работу со слоями. Тем не менее, это достаточно простая фича для реализации и её можно сделать. 
Нужно?

**Comment by 7kaiden7** [comment]
В любом случае это будет лучше чем пролистывать миллион обьектов до отдельной папки со слоями

**Comment by Yobas** [comment]
Ок, реализуем в 1.15

**Comment by 7kaiden7** [comment]
Безумно благодарен. Я схожу с ума когда трачу более 15 секунд на то, чтобы запихнуть пару обьектов в слой.

**Comment by Yobas** [comment]
Джем новый релиз платформы. В нем чехи улучшили работу со слоями

**Comment by Yobas** [comment]
В 69e3d19115d6020cc6e19b037c739bba9f522cf5 добавил возможность изменения слоёв. Естественно с множественным выбором объектов. Теперь работа со слоями не будет приносить столько боли

**Comment by 7kaiden7** [comment]
темка

**Comment by 7kaiden7** [comment]
закрываю задачу?

**Comment by Yobas** [comment]
> закрываю задачу?

она сама закроется когда коммит в котором упомянута эта задача попадёт в мастер
