### ISSUE TITLE
Убрать стан персонажа при падении из-за антистрейфа

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#257]
Убрать либо сильно уменьшить время стана при падении из-за антистрейфа.

Сейчас стан довольно продолжительный, и со стороны очень нелепо выглядит когда персонаж упал и не может встать, поэтому крутится вокруг своей оси.

**Comment by Yobas** [comment]
Так убрать или уменьшить? Сейчас стоит стан от 5 до 10 секунд.

**Comment by Sranych** [comment]
Я за то что бы убрать и посмотреть на обратную связь
