### ISSUE TITLE
Запрос функций ReNodes

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#281]
- [x] Функция добавления ключей для роли
- [x] ~~Функция добавления рандомного количества предметов в контейнер~~ **можно сделать**
- [x] Функции для получения настроек клиента (пол, имя, лицо, возраст и все то, что человек может настроить в лобби)
- [x] Функция создания патронов в магазине оружия
- [x] Функция для добавления стартового состояния (голод, но пока ничего больше нельзя)
- [ ] Функции для окончания режима, по истечению времени, по количеству мёртвых

**Comment by Yobas** [comment]
@Sranych второй пункт уже есть. Скопировать и вставить в любой граф.

```v1@{"nodes": {"0x2864a34e250": {"type_": "runtime_domain.RuntimeNode", "icon": "data\\icons\\icon_Blueprint_Loop_16x", "name": "Цикл в диапазоне", "color": [119, 119, 119, 255], "border_color": [74, 84, 85, 255], "text_color": [255, 255, 255, 180], "disabled": false, "selected": true, "visible": true, "width": 264.0, "height": 137.15, "pos": [1382.4135854953172, 570.1783660019596], "layout_direction": 0, "port_deletion_allowed": false, "subgraph_session": {}, "custom": {"Первый индекс": 1, "Последний индекс": 10}, "class_": "operators.for_loop"}, "0x2864423f410": {"type_": "runtime_domain.RuntimeNode", "icon": "data\\icons\\node_base.png", "name": "Случайное целое число", "color": [13, 18, 23, 255], "border_color": [74, 84, 85, 255], "text_color": [255, 255, 255, 180], "disabled": false, "selected": true, "visible": true, "width": 377.0, "height": 60, "pos": [1590.7270228454786, 726.3604207474692], "layout_direction": 0, "port_deletion_allowed": true, "subgraph_session": {}, "input_ports": [{"name": "Число 1", "multi_connection": false, "display_name": false, "color": [255, 255, 255, 255], "type": "", "style": null}, {"name": "Число 2", "multi_connection": false, "display_name": false, "color": [255, 255, 255, 255], "type": "", "style": null}], "output_ports": [{"name": "Результат", "multi_connection": true, "display_name": false, "color": [46, 139, 87, 255], "type": "int", "style": null}], "custom": {"autoportdata": {}}, "class_": "math.randomInt"}, "0x286442d8fd0": {"type_": "runtime_domain.RuntimeNode", "icon": "data\\icons\\node_base.png", "name": "Заметка 2", "color": [122, 140, 5, 255], "border_color": [74, 84, 85, 255], "text_color": [255, 255, 255, 180], "disabled": false, "selected": true, "visible": true, "width": 345.0, "height": 103.55, "pos": [1347.1265377877867, 458.44620395919446], "layout_direction": 0, "port_deletion_allowed": false, "subgraph_session": {}, "custom": {"text": "Создает 5-8 предметов в контейнере"}, "class_": "internal.sticker"}, "0x286438a9e50": {"type_": "runtime_domain.RuntimeNode", "icon": "data\\icons\\icon_BluePrintEditor_Function_16px", "name": "Создать предмет в контейнере", "color": [0, 69, 104], "border_color": [74, 84, 85, 255], "text_color": [255, 255, 255, 180], "disabled": false, "selected": true, "visible": true, "width": 322.0, "height": 118.25, "pos": [1727.9895380000403, 526.1551817747063], "layout_direction": 0, "port_deletion_allowed": false, "subgraph_session": {}, "custom": {"Тип предмета": "Item"}, "class_": "func.createItemInContainer"}, "0x2864a313010": {"type_": "runtime_domain.RuntimeNode", "icon": "data\\icons\\icon_BluePrintEditor_Function_16px", "name": "Создать буквальное целое число", "color": [52, 107, 43, 255], "border_color": [74, 84, 85, 255], "text_color": [255, 255, 255, 180], "disabled": false, "selected": true, "visible": true, "width": 350.0, "height": 73.1, "pos": [1257.8327031604629, 669.3146669254173], "layout_direction": 0, "port_deletion_allowed": false, "subgraph_session": {}, "custom": {"Значение": 5}, "class_": "math.makeLiteralInt"}, "0x286442df8d0": {"type_": "runtime_domain.RuntimeNode", "icon": "data\\icons\\icon_BluePrintEditor_Function_16px", "name": "Создать буквальное целое число", "color": [52, 107, 43, 255], "border_color": [74, 84, 85, 255], "text_color": [255, 255, 255, 180], "disabled": false, "selected": true, "visible": true, "width": 350.0, "height": 73.1, "pos": [1255.8680702915547, 743.4128961262903], "layout_direction": 0, "port_deletion_allowed": false, "subgraph_session": {}, "custom": {"Значение": 8}, "class_": "math.makeLiteralInt"}}, "connections": [{"in": ["0x2864a34e250", "Вход"], "out": ["0x28648489650", "Выход"]}, {"out": ["0x2864a34e250", "Тело цикла"], "in": ["0x286438a9e50", "Вход"]}]}```

**Comment by Yobas** [comment]
По последнему пункту: необходимость реализации завершения раунда по количеству умерших должно оставаться за пользователем. Для автоматической проверки по таймауту в следующем патче добавлен новый флаг в инспектор `Автопроверка длительности режима`. 
С количеством умерших добавлю пример в темплейте
