### ISSUE TITLE
Создать примеры игровой логики для ReNodes

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#282]
- [x] Пример события для завершения раунда при условии смерти определённых игроков
- [x] Пример присвоения ключа для роли
- [x] ~~Пример окончания режима по истечению времени~~
- [x] Пример окончания режима по количеству мёртвых

**Comment by Yobas** [comment]
Допускается ли вариант если все эти примеры будут в одном файле графа?

**Comment by Yobas** [comment]
Информация по примеру с ограничением на время: https://github.com/Relicta-Team/ReSDK_A3.vr/issues/281#issuecomment-1930462259
