### ISSUE TITLE
Ошибка на карте Template, minimap

### ISSUE THREAD

**Issue by 7kaiden7** [Relicta-Team/ReSDK_A3.vr#294]
Если в тестовом режиме запустить симуляцию с помощью пкм на карте и "С выбранным снарежением роли"  то игра зависнет навсегда либо просто выдаст ошибку. 

![Безымddянный](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/139656223/57e458cb-8f7b-446e-8d9f-21cced54e381)

Вот что выдаёт в консоли:
-> f:C:\Users\devil\Documents\Arma 3\mpmissions\ReSDK_A3.vr\src\Editor\Core\Core_perFrameHandler.sqf at 64 (scope:), lv:
[18:35:20] [REDIT::ERROR]       SCRIPT_ERROR: foreach: Тип Число,Не число, ожидался Массив,HashMap (file: RUNTIME_CODE at 81);
-> f: at 81 (scope:), lv: _foreachindex, _x, _roles, _curgamemode
-> f: at 84 (scope:), lv: _obj, _allroles, _uniqueroles, _atlpos, _objr, _screentoworldpos
-> f: at 9 (scope:), lv: _buttoncontext, _namecontext, _indexcontext, _this, _levelcontext
-> f:C:\Users\devil\Documents\Arma 3\mpmissions\ReSDK_A3.vr\src\Editor\Core\Core_perFrameHandler.sqf at 63 (scope:), lv: _foreachindex, _x
-> f:C:\Users\devil\Documents\Arma 3\mpmissions\ReSDK_A3.vr\src\Editor\Core\Core_perFrameHandler.sqf at 64 (scope:), lv:
[18:35:20] [REDIT::ERROR]       SCRIPT_ERROR: foreach: Тип Число,Не число, ожидался Массив,HashMap (file: RUNTIME_CODE at 81);
-> f: at 81 (scope:), lv: _foreachindex, _x, _roles, _curgamemode

И скрин вылета:
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/139656223/43d2bf35-3496-4e06-b597-81e7117e1105)

**Comment by Yobas** [comment]
Для скриптовых режимов (создаваемых через ReNode) судя по всему не правильно коллекционируются лобби и лейт роли: https://github.com/Relicta-Team/ReSDK_A3.vr/blob/5efc2f993daa385ad38944306cfc56e862c153d8/Src/Editor/Widgets/Widget_ContextMenu.sqf#L297
Исправление этой ошибки будет выпущено сегодня после полуночи
