### ISSUE TITLE
Сделать задачи для мобов в ReNode

### ISSUE THREAD

**Issue by 7kaiden7** [Relicta-Team/ReSDK_A3.vr#301]
Хочу сделать антагонистов с определенным задачами

**Comment by Yobas** [comment]
Возник вопрос касательно указания параметров задач. Хотел бы обсудить в войсе этот момент так как тут достаточно долго расписывать

**Comment by Yobas** [comment]
После сегодняшнего обсуждения было принято решение пробрасывать узлы всех задач (по категориям)

**Comment by Yobas** [comment]
не ту задачу пометил

**Comment by Yobas** [comment]
Эта сделана же...
