### ISSUE TITLE
Дополнение к библиотеке ReNode

### ISSUE THREAD

**Issue by 7kaiden7** [Relicta-Team/ReSDK_A3.vr#302]
- Создание магазина в оружии и патронов
- Создание проверки занята ли кровать и проверка есть ли свободные места в кровати. Чтобы при заходе за роль выбиралось место

**Comment by Yobas** [comment]
магазины - 03dd2fff90d8017774da97f7a564b164279019b6

**Comment by Yobas** [comment]
сидушки - 612aafa1fea92fdcb4e141628886658ac262acdf
