### ISSUE TITLE
Ошибка во время симуляции

### ISSUE THREAD

**Issue by 7kaiden7** [Relicta-Team/ReSDK_A3.vr#329]
После взаимодействия со стулом "Поднял - положил" 
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/139656223/f0ff1cb9-b70e-405a-885b-f7a44b65fe6f)

**Comment by Yobas** [comment]
https://github.com/Relicta-Team/ReSDK_A3.vr/blob/6acb0cce8336a87be5cfa693c2f9b0bd3b6de5b9/Src/host/GameObjects/GameObject.sqf#L1085
Исключение вызывается из-за того, что есть ассерт проверки что объект не должен являться стулом. Из-за ошибок в определении интерфейса `ISeat.Interface` все игровые объекты (даже моб) логически являются стулом... Поправил ошибку. Исправление выпущу в ближайшее время

**Comment by 7kaiden7** [comment]
РЕЛИКТА СТУЛ, Я СТУЛ, Голова СТУЛ😰😰🫣🫣🫣
