### ISSUE TITLE
Новые возможности взаимодействия с мобом

### ISSUE THREAD

**Issue by 7kaiden7** [Relicta-Team/ReSDK_A3.vr#334]
- ~~Дать урон~~
- Временное ослепление ?
- ~~Отрубить конечность~~
- ~~Сломать кость~~, ~~дать боль~~, дать кровотечение 
- ~~Стан на некоторое время~~
- ~~Положить в бессознанку на время~~
- ~~Заставить лечь~~

**Comment by Yobas** [comment]
Про временное ослепление. У нас никогда не было статус эффектов ослепления. Есть функция отключение видимости, но она достаточно низкоуровневая

**Comment by Yobas** [comment]
Кровотечение является результатом резаной или колотой раны. Его нельзя дать просто так
