### ISSUE TITLE
Отключить возможность выбора динамического освещения "Экспериментальное реликтово"

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#341]
При включении этой настройки ничего не видно
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/ba8fb513-2a2e-4bf0-a95a-1eeaea87fe48)

**Comment by Yobas** [comment]
В сегодняшнем обновлении мода вырезано
