### ISSUE TITLE
Жёлтый шарик

### ISSUE THREAD

**Issue by Irmos9** [Relicta-Team/ReSDK_A3.vr#344]
В Реедитор необходимо добавить команду, с помощью которой можно убрать/вернуть жёлтый шарик.

**Comment by Yobas** [comment]
В следующем патче можно будет выключить через настройки ReEditor
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/35444748/fa70a4b1-7870-4ed5-b59f-46bc1b1f008e)

Либо через команду `rcsphere 0` через окно команд в симуляции.
