### ISSUE TITLE
Неудобство в библиотеке объектов

### ISSUE THREAD

**Issue by Irmos9** [Relicta-Team/ReSDK_A3.vr#347]
Стоит только найти и выбрать предмет из списка, нажать клавишу "W" для того, чтобы чуть подвинуть камеру вперёд, как все объекты из библиотеки съезжают не пойми куда. Как я понимаю это некая функция сортировки предметов, но она очень мешает. Можно или убрать эту функцию, или перебиндить на другие клавиши, вот

**Comment by Yobas** [comment]
Из-за того, что фокус остается на виджете дерева библиотеки при нажатии на клавиши срабатывает внутренняя логика поиска по букве. Нужно либо снять фокус когда мышь уходит из виджета, либо как-то заблокировать инпут с клавиатуры для этого виджета
