### ISSUE TITLE
ReNode. Добавить узел на проверку и получение предмета в слоте.

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#360]
Нужен узел, с помощью которого можно получить есть ли предмет в слоте, и что это за предмет, что бы потом можно было из другого места вызвать создание предмета в этом контейнере.

**Comment by Yobas** [comment]
Добавим:
- Проверка занят ли слот инвентаря сущности
- Получить предмет в слоте сущности
