### ISSUE TITLE
ReNode. Доработки описания задач.

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#370]
Я хочу реализовать следующую логику:
- При определении антагонистов я выбираю среди них главного, беру первый индекс из массива антагов
- Главному антагонисту я показываю все возможные задачи, их название и описание
- Второстепенным антагонистам не должно выводиться название задач и их описание, а только общая вводная о том что у главного есть какая-то задача и у него об этом нужно уточнить.
- Дополнительно, я хочу выводить некое общее описание для всех антагонистов, что-то вроде вводной, некая предыстория. Например, при входе в игру, все возможные антаги видят информацию, что они являются членами одной преступной группы. Это описание должно быть отдельным от задач.

**Comment by Yobas** [comment]
Предложено следующее решение:
Добавляется новое свойство, отвечающее за кастомную логику описания. При включении данного свойства в воспоминаниях выводится только текст, возвращенный обработчиком описания задачи. Причем, если обработчик возвращает пустую строку - задача не отображается в воспоминаниях. 
Данное обновление позволит создавать скрытые задачи, а также создавать кастомную логику вывода текста задачи в воспоминаниях.
