### ISSUE TITLE
Поправить клетки

### ISSUE THREAD

**Issue by Yobas** [Relicta-Team/ReSDK_A3.vr#381]
По умолчанию клетки неизвестного типа

**Comment by Sranych** [comment]
Если речь про первый раунд на Спальнике, то лично мне удалось подоить мельтешка, и одного поймать

**Comment by Yobas** [comment]
> Если речь про первый раунд на Спальнике, то лично мне удалось подоить мельтешка, и одного поймать

А ты задавал в карте тип клеток? Потому что в первой сессии нового режима молочник вообще не мог сделать дело. Может у него навыка не хватало?

**Comment by Sranych** [comment]
Типы клеток заданы на карте, сегодня повторно проверил на проде. всё работает
