### ISSUE TITLE
Если убить сидящего моба, то последующее отрубание конечностей не будет отображаться на нём

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#394]
При убийстве сидящего моба, последующее отрубание конечностей не будет на нём отображаться. Если отрубить ему руку или ногу, визуально ничего не изменится, руки и ноги у него будут на месте.

1. Создать нового моба в симуляции
2. Посадить его на стул
3. Отрубить ему голову
4. Отрубить руку

Отрубленная рука визуально останется на месте.
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/eb1dd7dd-4482-4638-b7bd-c05e6cbd2fda)

Если то же самое сделать со стоящим мобом, проблема не воспроизводится.

**Comment by Yobas** [comment]
Это не работает с пустышками. У себя конечности отруюаются? Мне кажется на прошлых версиях так же было
