### ISSUE TITLE
Ломается позиция моба сидящего на скамейках/диванах/креслах с новыми анимациями бессознанки

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#395]
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/d7b2ce26-3713-4141-8c26-343410c6b91f)
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/edaf2db5-51c9-407b-82b4-f28c4a80c509)
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/44916183-35b3-4cbc-a90a-0729e33d871c)
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/b6f58358-3b7f-47fd-9db5-bc64d0374f38)

Кроме этого у сидящего мёртвого моба без рук, они торчат из спины
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/c539602c-2f93-4a29-9f4b-ab98ec58e9aa)

**Comment by Yobas** [comment]
Пришли пж в сознательном состоянии на этих же стульях насколько сильна разница по высоте?

**Comment by Sranych** [comment]
@Yobas 
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/a582a403-5411-4910-ad2b-88a64f69708f)
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/aefb8021-b216-4ccd-8217-ec3ba4be6da5)
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/20691c05-5222-4598-9c13-cddc3b72b2b9)
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/58831f08-b050-4121-88ad-d2be6ba47239)
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/ab63bc1f-3c8c-4a45-af87-78463d6de85b)

**Comment by Yobas** [comment]
Криво отображается только если персонаж без ног. Невозможно исправить.
