### ISSUE TITLE
В эмоут меню, кнопка которая разворачивает выпадающий список никак не выделяется, непонятно что это кнопка

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#397]
Предлагаю выделить её другим цветом, что бы было ясно что это кнопка. А еще лучше, если будет какой-то заголовок. Напрмиер название кнопки могло бы выглядеть так:
**меню**
(присесть)
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/b0da7cea-3d7b-4904-9455-47eff7769192)

**Comment by Yobas** [comment]
Наебнул стиля
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/35444748/58ebebb9-4a4b-498e-b7be-57f9e84e3907)
