### ISSUE TITLE
Проблема с наручниками

### ISSUE THREAD

**Issue by 7kaiden7** [Relicta-Team/ReSDK_A3.vr#403]
Я был без сознания и на меня надели наручники, визуально не было видно что я в наручниках. Я мог подбирать предметы и складывать, а так же заходить в комбат. Но остальные функции не работали. Нажал R и наручники сразу спали но не выпали как предмет, надписей в чате не было. На фрагменте видео в конце видно что я смог открыть свою одежду после звука наручников.
https://youtube.com/clip/Ugkxw9baEG_dVM2ABXcf45yDF6y9_Z5UTX7p?si=f8xdkjTlWjOkwXJN

И вот момент когда меня сковали наручниками: https://youtube.com/clip/UgkxTKwyTPgQc-S_S_LNjL96p8G7YuFuf9Og?si=B2JqVCu1cMQ7KNX6

Предполагаю что я зашёл в анимацию когда встал с безсознанки, нужно будет попробовать воспроизвести проблему.
Ещё другие игроки жаловались что наручники просто не работают, мы заковали румына но он нас всех в комбате перебил

**Comment by Sranych** [comment]
Вот такая ошибка при попытке надеть наручники
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/db4b2669-acc3-4cfb-9f26-b3483cb9f721)

**Comment by Yobas** [comment]
Дубликат имен функций setCustomAnimState
