### ISSUE TITLE
Проблемы с генерацией иконок объектов

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#434]
- [x] ~~Не создаётся папка ReSDK_A3.vr\Third-party\ImageConverter\icon_output~~ **не воспроизвелось**
- [x] ~~Если в папке scrennshots уже есть иконки, то генерация падает с ошибкой~~ **не воспроизвелось**
- [x] Не работает частичная генерация (генерация недостающих иконок), запускается генерация около 1300 иконок
- [x] Если включен курсор геометрии то он попадает на скриншот иконки

**Comment by Yobas** [comment]
По частичной генерации возможно тут проблема. 
https://github.com/Yobas/ReSDK_A3.vr/blob/744e62b7bf4f5048525662402ef14aea732756c8/Src/Editor/SystemTools/GenerateItemIcons.sqf#L225

В том куске кода удаляются картинки, которые ещё не были сгенерированы. Проверка гласит `если картинки нет, то удаляем её из списка на генерацию`. Таким образом он (пере)генерирует те картинки которые уже есть а отсутствующие пропустит.

**Comment by Yobas** [comment]
Первые 2 таски надо проверить так как логов нет, не понятно куда копать. Заодно и проверю ошибку частичной генерации и курсора
