### ISSUE TITLE
Таскание объектов

### ISSUE THREAD

**Issue by Yobas** [Relicta-Team/ReSDK_A3.vr#451]
# Принцип работы
Проверка возможности перемещения объекта выполняется на стороне сервера.
Принцип работы следующий:
1. Объекту включается режим wpos-трансформации. Он позволит быстро применять posworld и PBY-повороты.
2. Клиент выполняет запрос на хватание. Создается виртуальный объект привязки и запускается асинхронное задание обработки перемещения.
3. Клиенту отдается информация об указателе чтобы привязать целевой объект.
4. При открытии поворотного меню клиент вращает и поднимает объект. Для избежания мигания любых свойств объекта мы можем добавить его в блокирующую мапу `noe_client_set_lockedPropUpdates`.

## Выполнение на стороне сервера
Создается виртуальный объект. На него перемещается целевой объект. При удалении процесс сбрасывается. Во время проверки при смене позиции обновляется позиция. Валидность операции отдается первому держащему клиенту.

## Выполнение на стороне клиента
Создается виртуальный объект (бокс) под размер целевого объекта. Целевой объект плавно интерполируется под новые позиции если валидность позиции истинна. 
При открытии меню трансформации каждое изменение отправляется на сервер.

## Управление трансформом
- `LMB` - вращение объекта
- `LMB + Alt` - альтернативное вращение
- `RMB` - Поднятие и опускание объекта.

# Задачи
- [ ] Продумать работу системы и заполнить шапку..

# Описание системы
У некоторых объектов проставлен флаг `isMovable`, который позволяет тащить объект.
Таскание производится через хватание объекта. Для этого включается режим граба (F), либо прожимается ПКМ -> тащить.
Во время таскания у персонажа открывается ND-окно, в котором можно развернуть объект по 3м осям.
Так же объект можно поднимать с помощью колеса мыши.
При активном режиме перетаскивания персонаж испытывает перегруз. *Если вес персонажа меньше 2/3 от веса таскаемого объекта - процесс невозможен.*

---
## Устаревшая информация

Процесс перетаскивания.
Перетаскивание на стороне сервера происходит по следующим правилам:
1. Персонаж сдвигается в сторону
2. На сервер кидается запрос - 8 рейкастов от торса таскающего. если половина от них возможна, то мы отдаем клиенту новую позицию.
3. Клиенту отдается последняя позиция. Следующий запрос будет от неё.

Для клиента позиция плавно интерполируется.
---
Поправить:
- Поднятие итемов, которые грабнуты в данный момент
- Запрет посадки с драгаемым предметом
- Не отнимать владение объектом если другой персонаж тащит его

---
Для изменения трансформации интересную фичу предложил Астрал.
Она заключается в том, что перетаскивание предметов осуществляется с помощью зажатой мышки.
Реализовать следующим образом:
на nd дисплей вращения повестить обработчик мыши. колесо поднимает и опускает объект, движение вращает объект вокруг своей оси

**Comment by Yobas** [comment]
@Stellarthoughts последний абзац. Так хотел сделать?

**Comment by Stellarthoughts** [comment]
@Yobas Примерно так. На самом деле я сразу не понял, что ты хотел сделать перетаскивание для чего-то типа ящиков. Но я думаю мое предложение работает и для них. Чем тяжелее / массивнее предмет, тем дольше нужно удерживать мышку для перетаскивания.

**Comment by Yobas** [comment]
> @Yobas Примерно так. На самом деле я сразу не понял, что ты хотел сделать перетаскивание для чего-то типа ящиков. Но я думаю мое предложение работает и для них. Чем тяжелее / массивнее предмет, тем дольше нужно удерживать мышку для перетаскивания. 

Перетаскивание будет работать для всего, что можно тащить (включая итемы). При запуске таскания в руку кладется фейковый предмет(как при таскании персонажа). Таким образом мы добавляем нагрузку от тяжести переносимого объекта. Во время таскания персонаж не может двигаться вперёд и бегать. Отключение движения вперёд сделано для решения проблемы с *полетами* на объектах.
Во время таскания можно продолжить взаимодействовать с объектом с помощью пкм. Там же в пкм появляется новая кнопка (повернуть), которая активна только при процессе перетаскивания. При активации режима вращения открывается режим мыши. Перемещение по z колесом. Наклоны зажатием лкм.

**Comment by Yobas** [comment]
> Раз уж на то пошло, таскание персонажей можно сделать ровно так же, но с возможностью поворота! Это будет в тысячу раз удобнее чем то что есть сейчас @Yobas 
> 

На персонажей можно отдельную таску сделать. Их не успею поменять до субботы из-за сложностей с синхронизациями

**Comment by Yobas** [comment]
Текущая реализация работает, но имеет несколько проблем:
1. Графические артефакты при использовании освещения.
2. Вращение объекта - разность позиций и сложность синхронизации.
В данном случае самым оптимальный решением будет переписывание компонента под локального клиента. Валидацию оставляем так же на сервере. Рендер честный на клиенте и валидация позиций каждые 0.5 секунд. Днем буду тестировать подход

**Comment by Yobas** [comment]
Эту таску **надо** закрыть до конца этой недели. В течении следующего дня в шапке стоит с самого начала расписать принцип работы и особенности данной системы.
