### ISSUE TITLE
При попытке грибланства с кастомным источником света падает ошибка

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#457]
[08:26:24] ERROR: SCRIPT_ERROR: max: Тип Строка, ожидался Число,Не число (file: RUNTIME_CODE at 4);
-> f:getgameobjectonposition at 4 (scope:main), lv: _retchild=20, _vecpos=StreetLampEnabled#823, ___fn___="getgameobjectonposition", _dist="StreetLamp", _this=[StreetLampEnabled#824,StreetLampEnabled#823,"StreetLamp",[3812.25,4084.63,63.6246],20,true], _type=StreetLampEnabled#824, _retaslist=[3812.25,4084.63,63.6246]
-> f:unknown at 13 (scope:), lv:
-> f:FarmGarden::onUpdate at 11 (scope:), lv: ___fd___="C:\Users\Sranych\Documents\Arma 3\missions\ReSDK_A3.vr\src\host\GameObjects\Structures\Tools\Farming.sqf?198", ___fn___="FarmGarden::onUpdate", _this=[FarmGarden#916,262], _thisobj=FarmGarden#916
-> f:unknown at 11 (scope:), lv:
-> f:unknown at 9 (scope:), lv: _handle=262, _function=<CODE>, _x=[{private ___fn___ = "FarmGarden::onUpdate";private ___fd___ = "C:\Users\Sranych\Documents\Arma 3\missions\ReSDK_A3.vr\src\host\GameObjects\Structures\Tools\Farming.sqf?198";
private _thisobj = (_this select 0);
_thisobj setvariable ["timeLeft",(_thisobj , _args=FarmGarden#916, _delta=43559.3, _delay=1
-> f:unknown at 14 (scope:), lv: _ticktime=43559.3
-> f:x\cba\addons\common\XEH_postInit.sqf at 5 (scope:), lv:

**Comment by Yobas** [comment]
@Sranych привет. там скорее всего опять борьба с синтаксисом армы. Судя по смещенным параметрам там выполняется прибавление к возвращаемому значению и всё ломается. На грязноямске и иных картах этой проблемы не было из-за типов ламп (есть включенные, есть выключенные). 
Вобщем ошибка тут:
https://github.com/Relicta-Team/ReSDK_A3.vr/blob/ac132927c6ba3d823037c1618f8363e0b25b0c01/Src/host/GameObjects/Structures/Tools/Farming.sqf#L213

Я прошу тебя зайти у себя в `src\host\GameObjects\Structures\Tools\Farming.sqf` и на строке 213 обернуть вызов функции в скобки:
```sqf
	(["StreetLamp",getPosATL getSelf(loc),20,true] call getGameObjectOnPosition);
```

Проверь исчезнет ли проблема. Если всё ок то делай pr и закроем таску

**Comment by Yobas** [comment]
Исправлено в https://github.com/Yobas/ReSDK_A3.vr/commit/b83feafcd2ef9f0ab01951419633031c8db42758
Зальется в мастер вместе со следующим PR
