### ISSUE TITLE
Добавить возможность спавна определённых персонажей

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#46]
Седой, просьба реализовать функциональность которая позволит спавнить множество разновидностей персонажей.
- Требование 1. Что бы была возможность спавнить "Жрун"
- Требование 2. Возможность спавнить другие персонажи, например: "Голова", "Аббат", "Обывала", "Бригадир" и т.д.

**Comment by Yobas** [comment]
@Sranych добавляем в команду newmob указание класса создаваемой сущности. Пойдёт?

**Comment by Sranych** [comment]
@Yobas да, такой подход нам подходит, берите в работу, пожалуйста

**Comment by Yobas** [comment]
#47 - хорошо будет работать с этим

**Comment by Yobas** [comment]
@Sranych Команда `newmob` теперь принимает один или несколько опциональных параметров. 
`role=ROLECLASS`, где `ROLECLASS` - класснейм роли с которой будет выдана экипировка (одежда, оружие и тд).
`type=ENTITYCLASS`, где `ENTITYCLASS` - класснейм сущности, которая будет создана. (Женщина, жрну и тд). Обращаю внимание, что указание типа в большинстве случаев не будет менять визуальное отображение создаваемого персонажа, так как команда `newmob` существует только для отладки в среде симуляции.

Примеры использования:
```
newmob
newmob role=RCaretaker 
newmob role=RBum type=MobWoman
newmob type=Mob
```

**Comment by Yobas** [comment]
Будет добавлено вместе с #54
