### ISSUE TITLE
Тряпкой можно заткнуть рот игрока

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#465]
С помощью айтема rag можно заткнуть рот персонажу
![image](https://github.com/user-attachments/assets/0fc6ecb7-442e-4ad5-97be-89e6527d075b)

**Comment by Yobas** [comment]
Это что? Баг? Запрос на фичу? Не понимаю(((

**Comment by Yobas** [comment]
@Sranych Так он её зубами держит. Разве это запрещено?

**Comment by Sranych** [comment]
@Yobas это механика затыкания рта что бы персонаж  молчал, мне кажется что это проблема которую нужно решить, на твоё усмотрение

**Comment by Yobas** [comment]
Помоему так и было задумано судя по прописанной позиции для тряпки во рту

**Comment by Yobas** [comment]
@Stellarthoughts @7kaiden7 @Irmos9 @Italovich-Relicta парни, что думаете по этой теме? Стоит ли убрать визуальное отображение тряпки во рту?

**Comment by Stellarthoughts** [comment]
Очень жаль что модель нельзя заскейлить. Или хотя бы поменять ее вид для отображения во рту.

**Comment by Yobas** [comment]
> Очень жаль что модель нельзя заскейлить. Или хотя бы поменять ее вид для отображения во рту.

В новой системе мы можем добавить скейлинг модели для определенных слотов.

**Comment by Yobas** [comment]
Пока оставляем как есть. С новой системой привязки настроим размер в слоте
