### ISSUE TITLE
Работа с электроникой и прочей хуергой связанной с электричеством и активаторами в картомейкере

### ISSUE THREAD

**Issue by WhiTMBster** [Relicta-Team/ReSDK_A3.vr#472]
Я возможно плохо разбираюсь в том как тот или иной тамблер работает и как взаимодействуют между собой кнопки и электроника, но всё же хочу сказать что самое неудобное что есть в редакторе пока это работа с электрическими приборами, т.к. они отнимают больше времени чем простой билдинг сцены, как пример кнопки которые разделены на обычные и активаторы, и какого-то хрена у меня происходили ситуации, когда необходимо было то выбирать тумблер, то тумбер_активатор, и я не совсем принцип работы. Это на будущее или просто мусор? Что к чему вообще необходимо? Почему одно требует простую кнопку, другая электроника — кнопку с префиксом _активатор?

Далее, как я понимаю на реликте не получается экспериментировать с кнопками вообще. Объект либо имеет одну кнопку либо не имеет её вовсе, сделать активацию двери через две кнопки невозможно, ставить статус "вкл/выкл" тоже (при запуске все объекты уже активированы, как свет или кнопки). Недавно седой вообще заявил что громкоговоритель не может иметь связку из нескольких телефонов, т.е. на каждую войс-рубку по одному громкоговорителю. Не очень приятно.

Но я понимаю что в будущем это исправится и всё будет заебись, но захотелось в известность поставить, чтоб на будущее если что этот вопрос был поднят.

Ну или пусть седой/астра/другие мне ебало разнесут и объяснят что и как работает, а там уже разберёмся.

**Comment by Yobas** [comment]
Сразу предупрежу, что электричество будет изменено. Сейчас всё работает достаточно просто:
![Безымянный](https://github.com/user-attachments/assets/05b9cadc-a1ad-4be4-8610-57467d42fbc4)
Направление стрелок обозначает что и куда должно подключаться. Все приборы подключаются к источникам энергии, но не наоборот. 
generator - root-узел. во всех режимах это генератор. Просто и понятно
node - узел подключения. Щиток, кнопка или любой промежуточный проводник электричества.
endpoint - конечная точка. Она может брать энергию от родительского node, но не может отдавать её другим эндпоинтам или нодам. По сути это автодверь на электричестве, лампочка или любое электронное устройство типа консоли.

# Разница между кнопками
## Кнопки
При переключении состояния (вкл, выкл) обрубает или возвращает подачу энергии.

## Активаторы\переключатели (activator)
При активации такой кнопки на подключенные дочерние endpoint-ы посылается сигнал на выполнение действия. Это сейчас используется только в открытии\закрытии автоматических дверей.
