### ISSUE TITLE
Добавить возможность создавать кастомные таблички с текстом

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#48]
Нужна возможность создавать всякого рода разные таблички с текстом 
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/64296e50-02d2-4840-9e71-87dc07c369df)

**Comment by Yobas** [comment]
Сегодня возникла мысль а что если листы бумаги можно будет выкладывать на вертикальную поверхность информационной доски с объявлениями? Это наверное можно было бы быстрее сделать, чем таблички (к которым кстати я не помню чтобы были подходящие модели) и предмет, которым можно писать на них

**Comment by Yobas** [comment]
Визуализация текста на произвольных объектах не доступна. Есть хорошее альтернативное решение [#507](https://github.com/Relicta-Team/ReSDK_A3.vr/issues/507)
