### ISSUE TITLE
Привязка объектов к любым поверхностям

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#507]
Например, налепить бумагу на информационный щит
![image](https://github.com/user-attachments/assets/d80d5f84-748d-4f54-ad35-3edf0eb4875f)

**Comment by Yobas** [comment]
на тестах. мерж ночью

**Comment by Yobas** [comment]
@Sranych что у нас ещё кроме бумаги к инфодоске можно было бы привязывать к стенам\любым поверхностям?

**Comment by Sranych** [comment]
@Yobas Если речь идёт о том, что можно будет прикреплять какие-то другие предметы кроме бумаги к вертикальной поверхности, то наверное пока нет идей. 

Возможно у нас могут быть какие-то вертикальные стойки, например для оружия, или инструментов, но это наверное другая история.

**Comment by Sranych** [comment]
Если бы у нас были какие-то таблички, их бы можно было крепить. Но у нас их нет.
Картины у нас опять же в структурах.
Полки какие-нибудь может, не знаю, есть у нас такое что-то или нет.
Я думаю стоит подумать о том, что какую-то мебель можно было на стену вешать, например из того что крафтится не знаю, думайте

**Comment by Yobas** [comment]
> @Yobas Если речь идёт о том, что можно будет прикреплять какие-то другие предметы кроме бумаги к вертикальной поверхности, то наверное пока нет идей. 
> 
> Возможно у нас могут быть какие-то вертикальные стойки, например для оружия, или инструментов, но это наверное другая история.

Стойки для оружия на карте армии помню. Они не добавлены в библиотеку?

**Comment by Yobas** [comment]
Работа с логикой настенного выкладывания через `GameObject::canEmplaceItem`
