### ISSUE TITLE
Исправить проблему расстановки объектов из библиотеки

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#52]
Есть проблема что объекты улетают в стратосферу во время перетягивания из библиотеки, очень сильно нервы бъёт.
![image](https://github.com/Relicta-Team/ReSDK_A3.vr/assets/73469482/16727eda-f994-449f-8761-6451e3698f81)

**Comment by Yobas** [comment]
@Sranych не могу у себя воспроизвести проблему. Дай описание что ставишь и возле чего?
