### ISSUE TITLE
Медицина переработать!

### ISSUE THREAD

**Issue by 7kaiden7** [Relicta-Team/ReSDK_A3.vr#541]
Хочется чтобы чувак который весь отпизженный реально страдал! Надо чтобы стамина была меньше и он спотыкался какое-то время, голова гудела. Может лёгкое пробить ему, почки отбить. Ну людское короче

**Comment by Yobas** [comment]
Медицина и повреждения буду улучшать и дорабатывать в начале следующего года
https://github.com/orgs/Relicta-Team/projects/5/views/1?sliceBy%5Bvalue%5D=Medicine+rework

По этой таске не ясно что конкретно нужно сделать? Чтобы избивание лучше чествовалось? Это будет. Стамины итак не хватает при боевке. Спотыкание уже есть
