### ISSUE TITLE
Перекат с sqf

### ISSUE THREAD

**Issue by Yobas** [Relicta-Team/ReSDK_A3.vr#569]
Перепортирую богомерзкий sqf в любой нужный язык\синтаксис.
Ограничения:
- обязательная поддержка объектов с наследованием

Какие есть варианты:
- свой упрощенный c-like синтаксис со слабой типизацией
- js/ts
- c#/cpp (в крайне ограниченном виде)

Предложения, идеи? Кому надо, тот отпишется.

**Comment by lampyridae9** [comment]
SQF --> любой человеческий язык = с удовольствием бы вкатился в синтаксис и помог с разработкой
SQF --> JS/TS = тем более 
👍

**Comment by Yobas** [comment]
> SQF --> любой человеческий язык = с удовольствием бы вкатился в синтаксис и помог с разработкой SQF --> JS/TS = тем более 👍

нужно доки почитать, восполнить пробелы
собрал основные языковые фишки. в целом что-то типа такого получилось бы?
```js
//variables
var a, b, c; //multiple decl
var abc = 123; 
const var text = "hello"; //immutable var

//functions
function getname() {return "test"} //without params
function a_plus_b(a,b=0) { //with default param value
   return a + b;
}
var lambda = (a,b) => { return a + b;}
lambda(1,2)

//operators
if (true) {}
if (true) {} else if (false) {} else if (false) {} else {};
for (var i = 0; 100) {continue} //normal for can be used but its very slower in sqf
while (true) {break}

//modules
export function exp_example() {return "exported"}; //function for export
import exp_example from "./test.js"; //export data from other file


//classes
class TestClass {
    constructor() {};
    testmethod() {};
    field1 = "empty";
    fieldnum = 4321;
}
//inheritance
class Cls2 extends TestClass {
  field2 = true;
  field1 = "non-empty"; //override field
}

```

я покопал ts. на самом деле не вижу особого смысла прикручивать типизацию\шаблоны оттуда. возможно на такой вариант потребуется значительно больше времени и в целом придется больше рефакторить.

**Comment by lampyridae9** [comment]
Если типизацию прикручивать и создавать типы и интерфейсы всему - кучу времени займет да. JS прямолинейнее будет для переноса

Касаемо синтаксиса нормас, но отмечу

- Вместо устаревшего var используется let: вар находится в скоупе функции function(){тут} но не в скоупе блока if(){тут}  -  таким образом всплывает оттуда и рандомное поведение ожидаемо
ну и там еще больше всяких разных причин - побольше почитать: https://javascript.info/var#:~:text=%E2%80%9Cvar%E2%80%9D%20has%20no%20block%20scope&text=As%20var%20ignores%20code%20blocks,got%20a%20global%20variable%20test%20.&text=As%20we%20can%20see%2C%20var,is%20a%20remnant%20of%20that


Таким образом 
```js
//variables
let a, b, c; //multiple decl
let abc = 123; 
const text = "hello"; //immutable var

for (let i = 0; i < 100; i++) {
    continue;
}
```

И синтаксис for вот такой примерно ☝ остальное норм

**Comment by lampyridae9** [comment]
пока листал инет наткнулся на https://forums.bohemia.net/forums/topic/147227-javascript-for-arma/
вдруг будет полезно

**Comment by Yobas** [comment]
> пока листал инет наткнулся на https://forums.bohemia.net/forums/topic/147227-javascript-for-arma/ старо, но вдруг будет полезно 🤷‍♂️

Видел это. За десяток лет народ смог впихнуть разные языки в арму. Даже у нас для редактора прикостылен скриптинг на c#. 
Что до самого решения - оно не подходит, так как код крутится в своей изолированной среде и не связан с движком. В таком коде нет доступа к армовской информации - позиции моделей и прочая информация о геометрии\мире. Мы могли бы гонять трансформы и прочую необходимую информацию моделей в среду другого языка, но в таком случае из-за необходимости постоянных синхронизаций производительность будет если не хуже чем в нативном коде, то точно не лучше.

**Comment by Yobas** [comment]
> Если типизацию прикручивать и создавать типы и интерфейсы всему - кучу времени займет да. JS прямолинейнее будет для переноса
> 
> Касаемо синтаксиса нормас, но отмечу
> 
> * Вместо устаревшего var используется let: вар находится в скоупе функции function(){тут} но не в скоупе блока if(){тут}  -  таким образом всплывает оттуда и рандомное поведение ожидаемо
>   ну и там еще больше всяких разных причин - побольше почитать: https://javascript.info/var#:~:text=%E2%80%9Cvar%E2%80%9D%20has%20no%20block%20scope&text=As%20var%20ignores%20code%20blocks,got%20a%20global%20variable%20test%20.&text=As%20we%20can%20see%2C%20var,is%20a%20remnant%20of%20that
> 
> Таким образом
> 
> //variables
> let a, b, c; //multiple decl
> let abc = 123; 
> const text = "hello"; //immutable var
> 
> for (let i = 0; i < 100; i++) {
>     continue;
> }
> И синтаксис для _for_ вот такой примерно ☝ остальное норм

Представленный синтаксис имеет незначительные изменения с классическим js.

По поводу переменных предлагаю реализовать так: если переменная объявлена в root-скоупе то это глобальная переменная, являющаяся частью модуля. Переменные в функциях и их стейтментах существуют в них и во вложенных блоках. Что до ключевого слова `let` как по мне от него можно отказаться в пользу упрощения синтаксиса. 

Насчет for - я специально придумал пример с фиксированным for, так как в арме for с вычисляемыми стейтами есть, но работает в 2 раза медленнее и помечен устаревшим, существуя только для обратной совместимости. В текущем коде реликты не было ни одного момента когда нужно было бы внутри итерации изменить количество этих итераций.
Чтобы вырвиглазно не смотрелось (всё-таки condition требует bool а не number) можно сделать range-based по типу питона:
```js
for (var i of range(0,100,1)) {continue;} //range(begin,end,increment)
```

**Comment by Yobas** [comment]
@misnaged подключайся к обсуждению если заинтересован

**Comment by lampyridae9** [comment]
Насчет переменных - если будем использовать var в глобальном скоупе - то разницы думаю нет можем использовать вар
Касаемо for - выглядит окей

**Comment by Yobas** [comment]
Похоже всё таки typescript будет более предпочтителен в сравнении с js по следующим причинам:
- есть неймспейсы
- типизация (поможет решить текущее разделение между class/struct при доступе к членам)
- поля классов по умолчанию публичные неявно
- есть перечисления из коробки
- поддержка линтера в vscode из коробки + рабочие goto definitions

**Comment by Yobas** [comment]
У нашего текущего подмножества sqf наиболее лучшая консистентность c js/ts. Учитывая все перечисленные возможности языка в предыдущем посте + множество полезных github actions самым оптимальным вариантом будет typescript
