### ISSUE TITLE
Проблема при добавлении объекта без расширения файла в библиотеку

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReSDK_A3.vr#70]
Создать iStruct и выбрать для него простую модель без расширения файла, то при создании класса возникает ошибка. Объект добавляется в библиотеку, но у него нет иконки и остальные объекты типа iStruct не заменяются автоматически. 

Примеры моделей:
a3\structures_f_enoch\walls\brick\brickwall_04_l_5m_old_f
a3\structures_f_enoch\walls\brick\brickwall_01_l_5m_f

**Comment by Yobas** [comment]
ошибка поймана тут. проблема из-за отсутствующего расширения в пути до модели
https://github.com/Relicta-Team/ReSDK_A3.vr/blob/1a6771040080d92d268bdddd0910cd66e822f256/Src/Editor/GameObjectsLibrary/GOLib_modelAssoc.sqf#L80

**Comment by Yobas** [comment]
Банк моделей криво сгенерился в M2C.sqf
