### ISSUE TITLE
Добавить свойство для контейнеров, которые нельзя открыть (установка через инспектор)

### ISSUE THREAD

**Issue by 7kaiden7** [Relicta-Team/ReSDK_A3.vr#87]

**Comment by 7kaiden7** [comment]
а лучше два килограмма

**Comment by Yobas** [comment]
@7kaiden7 у нас в интерфейсном файле контейнера есть свойство, позволяющее полностью заблокировать его открытие и укладывание в него предметов. Такое свойство пойдёт?

**Comment by 7kaiden7** [comment]
Я думаю да!

**Comment by Yobas** [comment]
В контейнерах ищи свойство (чекбокс) с названием *"Открытый контейнер"*
